### PR TITLE
Feature/21 continue unit testing

### LINKED ISSUE #21: Continue Unit Testing
Had to merge #10 because it had structural changes that are important to future additions. Continuing unit testing on this issue.

### PR DESCRIPTION
**Pull request by gregdeane**
This PR includes changes from PR #20. Please approve and merge that PR first.

~~We will be removing the controller spec file since controller methods are accessed and tested through these component tests.~~ Scratch that. There are a couple of cookie calls that can be spied upon and tested in a controller spec. That will be in an upcoming PR.

Closes #21

### CODE REVIEW

**Comment by cjhowald** [comment]
Merged from master to get a cleaner diff, since #20 has already merged.

**Comment by cjhowald** [comment]
Unit tests & manual testing pass. Test code looks good. Nice work figuring out the angular types needed for testing.

**Comment by cjhowald** [comment]
👍

**Comment by gregdeane** [comment]
👍

**Pull request merged**
